### PR TITLE
update x/tools

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by bflad** [comment]
@remyleone can you ensure that all the files from `go mod vendor` are added as well? Thanks!

**Comment by bflad** [comment]
_Very strange_:

```
--- FAIL: TestAnalyzerFixes (1.19s)
Error:     analysistest.go:229: /home/runner/work/tfproviderlint/tfproviderlint/xpasses/XR007/testdata/src/a/alias.go: error formatting resulting source: 9:6: expected '(', found fAlias (and 1 more errors)
        package a
        
        import (
        	e "os/exec"
        )
        
        var failingAlias =  // want "avoid os/exec.Command"
        
        func fAlias() {
        	 // want "avoid os/exec.Command"
        
        	failingAlias("true")
        }
```

https://github.com/bflad/tfproviderlint/blob/9717018be82635e82809d1f68179793bfe088e12/xpasses/XR007/testdata/src/a/alias.go

```go
package a

import (
	e "os/exec"
)

var failingAlias = e.Command // want "avoid os/exec.Command"

func fAlias() {
	e.Command("true") // want "avoid os/exec.Command"

	failingAlias("true")
}
```

Maybe switching those files to this syntax will fix them as a quick fix for whatever is going on differently in x/tools:

```go
var (
  // ... 
)
```

**Comment by mattburgess** [comment]
If it helps any, I bisected those test failures down to v0.1.8. v0.1.7 passes fine. Interestingly, and _maybe_ related, it's v0.1.8 that introduces the original issue this was intended to fix, namely #255 which I happen to be hitting trying to run `make providerlint` on the AWS provider.

**Comment by bflad** [comment]
After some rigamarole with needing to upgrade Go (#269) and then x/tools (#270), this should be resolved in the upcoming v0.29.0 release 🔜 . Thanks for submitting this and sorry for the delayed resolution.

**Pull request closed without merging**
